### ISSUE TITLE
Should logout delete all expired tokens?

### ISSUE THREAD

**Issue by shaahink** [VahidN/JwtWithWebAPI#2]
The way [logout ](https://github.com/VahidN/JwtWithWebAPI/blob/master/JwtWithWebAPI/Controllers/UserController.cs#L29) implemented, it does delete expired tokens for every user. That would cause a problem in the following scenario: 

a)User-a logs into the system
b)User-b logs into the system 
c)User-a's token gets expired but his refresh token is still valid
d)User-b logs out of the system and Logout operation deletes the expired token of User-a as well. 
e)User-a tries to call a server API, the server returns unauthorised 401, the client attempts to refresh the token, it will fail as there's no token stored in the database. 

I assume if [the condition](https://github.com/VahidN/JwtWithWebAPI/blob/master/JwtWithWebAPI.Services/TokenStoreService.cs#L34) of finding expired tokens change from 
`_tokens.Where(x => x.AccessTokenExpirationDateTime < now).` 
to
`_tokens.Where(x => x.RefreshTokenExpiresUtc< now).`

That should fix the problem? If you agree I am happy to submit a pull request.

**Comment by VahidN** [comment]
It's better to delete all tokens of the current user (this is the main point of the user's logout) and delete expired RefreshToken's of the other users.

**Comment by VahidN** [comment]
Added via https://github.com/VahidN/JwtWithWebAPI/commit/2bee8e359b661ff6953ab036f8d7467f51b0cebc
