### ISSUE TITLE
Which bit of the logic checks if RefreshToken is valid?

### ISSUE THREAD

**Issue by shaahink** [VahidN/JwtWithWebAPI#3]
Assuming there's a token in database which both AccessTokenExpirationDateTime and RefreshTokenExpiresUtc are expired. Do we need to check if the Token is valid when a user attempts to Refresh his token? 

In RefreshTokenProvider.Receive, there's no check to see if the Token is actually valid based on the RefreshTokenExpiresUtc.

**Comment by VahidN** [comment]
If a token is not valid, `FindToken` will return null, because its hash, is the hash of the entire token, including times and claims, etc.
