### ISSUE TITLE
Why property  is type of Fuc<IService> ?

### ISSUE THREAD

**Issue by xsoheilalizadeh** [VahidN/JwtWithWebAPI#4]
Hi, why you use ` Func<ITokenStoreService>` instead of `ITokenStoreService` in property , what is your reason?

https://github.com/VahidN/JwtWithWebAPI/blob/c72865974ba27201741b5016f86b53f725202cb6/JwtWithWebAPI/JsonWebTokenConfig/JwtAuthorizeAttribute.cs#L21

**Comment by VahidN** [comment]
To make its lifetime transient. more info [^](http://www.dotnettips.info/courses/topic/5/6a63a4a7-c7d4-4f19-aee4-31cf69068a9c#comment-618) & [^](http://www.dotnettips.info/courses/topic/5/a727a21b-5cec-4dbd-95f0-91d87e2218e5#comment-574)
